-- Logs de autenticação para a central administrativa.
-- Eventos de senha são gravados somente pela Edge Function security-login.
-- A trilha transacional continua na auditoria canônica append-only existente.
-- Escopo intencionalmente global: somente ADMIN ativo da plataforma consulta qualquer tenant;
-- não reutilizar estas RPCs em superfícies tenant_admin.

CREATE TABLE IF NOT EXISTS public.security_login_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_user_id uuid,
  identifier_masked text NOT NULL DEFAULT '—' CHECK (char_length(identifier_masked) <= 180),
  identifier_tag text NOT NULL CHECK (identifier_tag ~ '^[0-9a-f]{64}$'),
  provider text NOT NULL CHECK (provider IN ('password', 'oauth')),
  outcome text NOT NULL CHECK (outcome IN ('pending', 'success', 'failure')),
  reason_code text CHECK (reason_code IS NULL OR reason_code IN ('invalid_credentials', 'rate_limited', 'auth_service_error', 'profile_inactive', 'profile_missing')),
  ip_address text CHECK (ip_address IS NULL OR char_length(ip_address) <= 64),
  user_agent text CHECK (user_agent IS NULL OR char_length(user_agent) <= 512),
  created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);

CREATE INDEX IF NOT EXISTS security_login_events_created_idx
  ON public.security_login_events (created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS security_login_events_identifier_idx
  ON public.security_login_events (identifier_tag, created_at DESC)
  WHERE outcome = 'failure';
CREATE INDEX IF NOT EXISTS security_login_events_ip_idx
  ON public.security_login_events (ip_address, created_at DESC)
  WHERE outcome = 'failure';

ALTER TABLE public.security_login_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.security_login_events FROM PUBLIC, anon, authenticated;
GRANT INSERT ON public.security_login_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.security_login_events_id_seq TO service_role;

COMMENT ON TABLE public.security_login_events IS
  'Eventos de autenticação capturados no backend; somente RPCs administrativas os expõem. Retenção operacional de 180 dias.';
COMMENT ON COLUMN public.security_login_events.identifier_tag IS
  'HMAC-SHA-256 do e-mail normalizado, com chave somente do backend, usado para correlação e limitação; o e-mail integral não é armazenado.';
COMMENT ON COLUMN public.security_login_events.identifier_masked IS
  'Identificador mascarado para consulta administrativa, sem armazenar o e-mail completo.';
COMMENT ON COLUMN public.security_login_events.reason_code IS
  'Código fechado; nunca contém mensagem bruta da Auth, senha, token ou corpo da requisição.';

-- A função pública é referenciada por RPCs existentes do painel. Cria-se somente
-- quando ausente, usando o helper de ADMIN ativo definido nas migrations do projeto.
DO $admin_helper$
BEGIN
  IF to_regprocedure('public.fn_is_admin()') IS NULL THEN
    EXECUTE $create$
      CREATE FUNCTION public.fn_is_admin()
      RETURNS boolean
      LANGUAGE sql STABLE SECURITY DEFINER
      SET search_path = pg_catalog, public, app_private
      AS $body$ SELECT app_private.current_user_is_admin(); $body$
    $create$;
    REVOKE ALL ON FUNCTION public.fn_is_admin() FROM PUBLIC, anon;
    GRANT EXECUTE ON FUNCTION public.fn_is_admin() TO authenticated;
  END IF;
END;
$admin_helper$;

CREATE OR REPLACE FUNCTION public.security_login_begin_attempt(
  p_identifier_masked text,
  p_identifier_tag text,
  p_ip_address text,
  p_user_agent text
)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, app_private, pg_temp
AS $begin$
DECLARE
  v_now timestamptz := clock_timestamp();
  v_tag_lock bigint;
  v_ip_lock bigint;
  v_tag_count bigint;
  v_ip_count bigint := 0;
  v_event_id bigint;
  v_limited boolean;
BEGIN
  IF p_identifier_tag IS NULL OR p_identifier_tag !~ '^[0-9a-f]{64}$'
     OR p_identifier_masked IS NULL OR char_length(p_identifier_masked) > 180
     OR (p_ip_address IS NOT NULL AND char_length(p_ip_address) > 64)
     OR (p_user_agent IS NOT NULL AND char_length(p_user_agent) > 512) THEN
    RAISE EXCEPTION 'Invalid login-audit parameters' USING ERRCODE = '22023';
  END IF;

  v_tag_lock := hashtextextended('security-login:identifier:' || p_identifier_tag, 0);
  IF p_ip_address IS NULL THEN
    PERFORM pg_advisory_xact_lock(v_tag_lock);
  ELSE
    v_ip_lock := hashtextextended('security-login:ip:' || p_ip_address, 0);
    IF v_tag_lock = v_ip_lock THEN
      PERFORM pg_advisory_xact_lock(v_tag_lock);
    ELSE
      PERFORM pg_advisory_xact_lock(least(v_tag_lock, v_ip_lock));
      PERFORM pg_advisory_xact_lock(greatest(v_tag_lock, v_ip_lock));
    END IF;
  END IF;

  SELECT count(*) INTO v_tag_count
  FROM public.security_login_events
  WHERE identifier_tag = p_identifier_tag
    AND created_at >= v_now - interval '15 minutes'
    AND outcome IN ('failure', 'pending');

  IF p_ip_address IS NOT NULL THEN
    SELECT count(*) INTO v_ip_count
    FROM public.security_login_events
    WHERE ip_address = p_ip_address
      AND created_at >= v_now - interval '15 minutes'
      AND outcome IN ('failure', 'pending');
  END IF;

  v_limited := v_tag_count >= 8 OR v_ip_count >= 30;
  INSERT INTO public.security_login_events(
    auth_user_id, identifier_masked, identifier_tag, provider, outcome,
    reason_code, ip_address, user_agent
  ) VALUES (
    NULL, p_identifier_masked, p_identifier_tag, 'password',
    CASE WHEN v_limited THEN 'failure' ELSE 'pending' END,
    CASE WHEN v_limited THEN 'rate_limited' ELSE NULL END,
    p_ip_address, p_user_agent
  ) RETURNING id INTO v_event_id;

  RETURN jsonb_build_object('allowed', NOT v_limited, 'event_id', v_event_id);
END;
$begin$;

CREATE OR REPLACE FUNCTION public.security_login_finish_attempt(
  p_event_id bigint,
  p_auth_user_id uuid,
  p_outcome text,
  p_reason_code text
)
RETURNS void
LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public, app_private, pg_temp
AS $finish$
BEGIN
  IF p_outcome IS NULL OR p_outcome NOT IN ('success', 'failure')
     OR (p_outcome = 'success' AND p_reason_code IS NOT NULL)
     OR (p_outcome = 'failure' AND (p_reason_code IS NULL OR p_reason_code NOT IN ('invalid_credentials', 'rate_limited', 'auth_service_error', 'profile_inactive', 'profile_missing'))) THEN
    RAISE EXCEPTION 'Invalid login-audit result' USING ERRCODE = '22023';
  END IF;

  UPDATE public.security_login_events
  SET auth_user_id = p_auth_user_id, outcome = p_outcome, reason_code = p_reason_code
  WHERE id = p_event_id AND outcome = 'pending';
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Pending login-audit event not found' USING ERRCODE = 'P0002';
  END IF;
END;
$finish$;

REVOKE ALL ON FUNCTION public.security_login_begin_attempt(text, text, text, text) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.security_login_finish_attempt(bigint, uuid, text, text) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.security_login_begin_attempt(text, text, text, text) TO service_role;
GRANT EXECUTE ON FUNCTION public.security_login_finish_attempt(bigint, uuid, text, text) TO service_role;

CREATE OR REPLACE FUNCTION public.admin_security_overview()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, app_private, pg_temp
AS $function$
DECLARE
  result jsonb;
BEGIN
  IF NOT app_private.current_user_is_admin() THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'Apenas administradores podem consultar os registros de segurança.';
  END IF;

  SELECT jsonb_build_object(
    'janela_dias', 180,
    'logins_24h', (SELECT count(*) FROM public.security_login_events WHERE created_at >= now() - interval '24 hours' AND outcome IN ('success', 'failure')),
    'falhas_24h', (SELECT count(*) FROM public.security_login_events WHERE created_at >= now() - interval '24 hours' AND outcome = 'failure'),
    'sucessos_24h', (SELECT count(*) FROM public.security_login_events WHERE created_at >= now() - interval '24 hours' AND outcome = 'success'),
    'ips_distintos_24h', (SELECT count(DISTINCT ip_address) FROM public.security_login_events WHERE created_at >= now() - interval '24 hours' AND outcome IN ('success', 'failure') AND ip_address IS NOT NULL),
    'transacoes_24h', (SELECT count(*) FROM public.auditoria_eventos WHERE ocorrido_em >= now() - interval '24 hours'),
    'acessos_recentes', coalesce((
      SELECT jsonb_agg(to_jsonb(e) ORDER BY e.created_at DESC)
      FROM (
        SELECT id, identifier_masked, provider, outcome, reason_code, ip_address, user_agent, created_at
        FROM public.security_login_events
        WHERE created_at >= now() - interval '180 days' AND outcome IN ('success', 'failure')
        ORDER BY created_at DESC, id DESC
        LIMIT 6
      ) e
    ), '[]'::jsonb)
  ) INTO result;

  RETURN result;
END;
$function$;

CREATE OR REPLACE FUNCTION public.admin_security_activity(
  p_category text DEFAULT 'all',
  p_period text DEFAULT '30d',
  p_search text DEFAULT '',
  p_page integer DEFAULT 0,
  p_page_size integer DEFAULT 25
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public, app_private, pg_temp
AS $function$
DECLARE
  result jsonb;
  v_category text := lower(coalesce(p_category, 'all'));
  v_period text := lower(coalesce(p_period, '30d'));
  v_search text := left(trim(coalesce(p_search, '')), 120);
  v_page integer := greatest(0, least(coalesce(p_page, 0), 200));
  v_page_size integer := greatest(1, least(coalesce(p_page_size, 25), 50));
  v_since timestamptz;
BEGIN
  IF NOT app_private.current_user_is_admin() THEN
    RAISE EXCEPTION USING ERRCODE = '42501', MESSAGE = 'Apenas administradores podem consultar os registros de segurança.';
  END IF;

  IF v_category NOT IN ('all', 'access', 'transactions') THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'Categoria de auditoria inválida.';
  END IF;
  IF v_period NOT IN ('24h', '7d', '30d', '180d') THEN
    RAISE EXCEPTION USING ERRCODE = '22023', MESSAGE = 'Período de auditoria inválido.';
  END IF;

  v_since := now() - CASE v_period
    WHEN '24h' THEN interval '24 hours'
    WHEN '7d' THEN interval '7 days'
    WHEN '30d' THEN interval '30 days'
    ELSE interval '180 days'
  END;

  WITH all_events AS (
    SELECT
      s.id::text AS event_id,
      'access'::text AS category,
      'login'::text AS event_type,
      s.outcome,
      coalesce(u.nome, s.identifier_masked) AS actor,
      s.identifier_masked,
      NULL::text AS entity,
      NULL::text AS entity_id,
      s.ip_address,
      s.user_agent,
      s.reason_code,
      '[]'::jsonb AS changed_fields,
      s.created_at AS event_at,
      s.provider AS source
    FROM public.security_login_events s
    LEFT JOIN public.usuarios u ON u.uuid = s.auth_user_id
    WHERE s.created_at >= v_since
      AND s.outcome IN ('success', 'failure')

    UNION ALL

    -- Fonte nativa para provedores externos. A consulta permanece compatível
    -- quando o armazenamento Postgres de Auth Audit Logs está vazio/desativado.
    SELECT
      a.id::text AS event_id,
      'access'::text AS category,
      coalesce(a.payload::jsonb->>'action', 'login') AS event_type,
      CASE WHEN a.payload::jsonb ? 'error' OR a.payload::jsonb ? 'error_code' THEN 'failure' ELSE 'attempt' END AS outcome,
      coalesce(u.nome, 'Autenticação Supabase') AS actor,
      NULL::text AS identifier_masked,
      NULL::text AS entity,
      NULL::text AS entity_id,
      a.ip_address::text AS ip_address,
      a.payload::jsonb->>'user_agent' AS user_agent,
      CASE WHEN a.payload::jsonb ? 'error' OR a.payload::jsonb ? 'error_code' THEN 'auth_rejected' ELSE NULL END AS reason_code,
      '[]'::jsonb AS changed_fields,
      a.created_at AS event_at,
      'supabase_auth'::text AS source
    FROM auth.audit_log_entries a
    LEFT JOIN public.usuarios u ON u.uuid = CASE
      WHEN a.payload::jsonb->>'user_id' ~* '^[0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12}$'
      THEN (a.payload::jsonb->>'user_id')::uuid
      ELSE NULL::uuid
    END
    WHERE a.created_at >= v_since
      AND a.payload::jsonb->>'action' = 'login'
      AND coalesce(a.payload::jsonb->'metadata'->>'provider', '') <> 'email'

    UNION ALL

    SELECT
      ae.id::text AS event_id,
      'transactions'::text AS category,
      ae.operacao AS event_type,
      'recorded'::text AS outcome,
      coalesce(u.nome, 'Sistema') AS actor,
      NULL::text AS identifier_masked,
      ae.entidade AS entity,
      ae.entidade_id::text,
      ae.ip_address::text AS ip_address,
      ae.user_agent::text AS user_agent,
      NULL::text AS reason_code,
      coalesce(ae.campos_alterados, '[]'::jsonb) AS changed_fields,
      ae.ocorrido_em AS event_at,
      ae.origem AS source
    FROM public.auditoria_eventos ae
    LEFT JOIN public.usuarios u ON u.id = ae.ator_id
    WHERE ae.ocorrido_em >= v_since
  ), filtered AS (
    SELECT *
    FROM all_events e
    WHERE (v_category = 'all' OR e.category = v_category)
      AND (
        v_search = '' OR position(lower(v_search) IN lower(concat_ws(' ', e.actor, e.identifier_masked, e.event_type, e.outcome, e.entity, e.entity_id, e.ip_address, e.reason_code))) > 0
      )
  ), paginated AS (
    SELECT *
    FROM filtered
    ORDER BY event_at DESC, event_id DESC
    LIMIT v_page_size OFFSET (v_page * v_page_size)
  )
  SELECT jsonb_build_object(
    'total', (SELECT count(*) FROM filtered),
    'page', v_page,
    'page_size', v_page_size,
    'items', coalesce((SELECT jsonb_agg(to_jsonb(p) ORDER BY p.event_at DESC, p.event_id DESC) FROM paginated p), '[]'::jsonb)
  ) INTO result;

  RETURN result;
END;
$function$;

REVOKE ALL ON FUNCTION public.admin_security_overview() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.admin_security_activity(text, text, text, integer, integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.admin_security_overview() TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_security_activity(text, text, text, integer, integer) TO authenticated;

-- Limpeza física obrigatória: o deploy falha se o banco não puder aplicar a retenção.
DO $retention$
DECLARE
  v_job_id bigint;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_extension WHERE extname = 'pg_cron')
     OR to_regclass('cron.job') IS NULL THEN
    RAISE EXCEPTION 'pg_cron is required to enforce 180-day physical retention';
  END IF;

  FOR v_job_id IN
    SELECT jobid FROM cron.job
    WHERE jobname IN ('security-login-retention-180d', 'security-login-pending-cleanup')
  LOOP
    PERFORM cron.unschedule(v_job_id);
  END LOOP;
  PERFORM cron.schedule(
    'security-login-pending-cleanup',
    '*/5 * * * *',
    'UPDATE public.security_login_events SET outcome = ''failure'', reason_code = ''auth_service_error'' WHERE outcome = ''pending'' AND created_at < now() - interval ''5 minutes'';'
  );
  PERFORM cron.schedule(
    'security-login-retention-180d',
    '0 * * * *',
    'DELETE FROM public.security_login_events WHERE created_at < now() - interval ''180 days'';'
  );
END;
$retention$;
